# -*- coding: utf-8 -*-
"""TTL_IoT Firebase write.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m3z7N1U6GdtUaHnsFcrjCK4iE__pO2os

## **Import libraries**
"""

pip install --upgrade firebase-admin

import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
from firebase_admin import db

from datetime import datetime, date, timedelta

"""## **Create Credentials**




"""

cred = firebase_admin.credentials.Certificate({
  "type": "service_account",
  "project_id": "ttl-iot",
  "private_key_id": "60b933117f50f3e8a5d091b27ee11eaf07864dcc",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDF9rsiYucpimKw\nbQtwkFyPNf+xqmewJqh+kafsAgoRqcs4erwBxQq1iWvfu7b1vub4FFkdUCfi/X4s\nIG4gIH07BwAvWciy8pawibbd6LazobyCdEJ4ODuEAoeEbmELLLU58nlyHTZJ2UMC\nFozklhu61E+xuvAXA83xRq/Y4KahIfiV8QX9IFVk0Sk72X8D1/lpiZMuY5zijCN8\np6udtNBH/N3FBYcKASkdMKzQx5sVE/mQG7NUussc4uQw6tI/QG6DzzznxVI8VwwT\nKKmFPkczrNm9ak9PFOGV8t9dgJPnN7fY9GHUegBK58OCJMqvLW+3zTiOvZWI+cI4\nTddAIdNzAgMBAAECggEAJ1xH1+3vRVCpD6gWwrJJXQYhCUu24wzEqqm+SAwdwWZP\nrDKnB/kMCI1CwBDcL19eIAw3rb7et2CsggyOqN+c1qwtKr0AzSezs3UmQVgAX5X0\nW8HO54VSvAwessOZkvW4MMXXxMsvHJ7Qlm0yZU69Q7fsAowHKaRNgcAKvaXpK5cx\nz7s6zoA7P/TKBOkeW8GSth398saq9+ZN/Sa38gcD6J5tUg+77pkn7/EEygg1UVw9\nRb3CMETKgWnDNT40Wzf4TLxc3Xixbt7nnry0wC5dBOw5H55M3QQzd04T1pJqGPTd\neqwllzBQF8HTBvBaKl1FnOH+esbnX5HuEontrW6CbQKBgQD/dE/GBXQ0MfHkpaJc\nK4Vh3es3i7rRAKiekSv8N5Fm4bRy79BIMzwsxu0q5Juqmh+voPPJh8WFrXwHDCwq\nHy+zDKk/SQuvIVSo2eH9L/vH6mrlFTiScuGY4EKr+5qjtJwhiD1NONSTqtOjMzWa\nqi436VlmjJ07hTDUl2VKWkLVtQKBgQDGYvtx5M+vNSuD7pxeJko7r46t0e+Jok7o\nWaew1pCHLjnDLp3pKkOf3sGzT+fbvguCDdKy/zksSLQNKyk0vpqZZ5hg+WQrC9X3\nugfsZElwLrN19jD2SiYrpyEsZ7LdVwDLwJQGx8D7gENhLMqkwMlZOLyBFImDzYQd\nVIYeXHs9hwKBgQDx68PUo7ud5qLPR7FQGoMx4MlujCy63CXULWV7cWCJDz0mEEiu\n556YRTe8BE4LrfRODl5xv9vmshogTn3Q0kIJDfeGkHW5QBZ95gHoFjYa6LydAJDX\n2GYfslpRp3CWkme+NdjgNe7Tfdb52nhsZbhpiNr6jDYndQZ+fnYViQ98dQKBgD3O\npMwNH29Uv2PxOSJUB5ikz2z0FQ7qVG8rT4VWs9yJ2FEo+uWj10G9otd8s53QjcFN\nETHXNjbHx+C6a7IVGBFnJyA/UqfeniD6AnHxpLegtSSxOPviihXbkghFnoI7EvJn\n4zZhkYxJn7Rswg2mSpTTilck0NsRcnG43bgj0/mNAoGATd8eQ1EHIuLvlF+beH/T\nvMX0XUOevN/QzVamQhbDz8o8VFwZfVGLj9fTheBElWj3FPGDub3fb2DPu9AO6+LJ\n9MGlsbQtktdi7ZP6xnbGLlAigd2Yc8t7+mlTaJNqBoCMCb074O91JGX40GwxZigU\nCXBPJDZX550+Lbt3pvtftCw=\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-yrbg2@ttl-iot.iam.gserviceaccount.com",
  "client_id": "102474256127526520693",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-yrbg2%40ttl-iot.iam.gserviceaccount.com"
})
try:
  firebase_admin.initialize_app(cred, {
    'databaseURL': 'https://ttl-iot-default-rtdb.europe-west1.firebasedatabase.app'
})  # Initialize the app with a service account, granting admin privileges
except ValueError:
  print('Firebase - Already initialized')
except:
  print('Firebase - Error occured')
else:
  print('Firebase - Initialized Successfully')

"""## **Initiliaze Firestore Client & Realtime database**"""

ref = db.reference('CheckLive')

"""## **Write to Data**"""

print("Writing to Firebase")
now = datetime.now()
current_time = now.strftime("%y-%m-%d %H:%M:%S")
print("Current Time =", current_time)
# ref.get()
ref.set(current_time)

