name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
            architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: python -m pip install --upgrade pip
      - run: python -m pip install --upgrade firebase_admin
      - run: python firebase_write.py "$FIREBASE_SA_JSON"
        env:
            FIREBASE_SA_JSON: '${{ secrets.FIREBASE_SA_JSON}}'

      